# Generated by Django 5.2.4 on 2025-10-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(choices=[(False, 'Обычная'), (True, 'Важная')], default=False, verbose_name='Важная новость'),
        ),
    ]
