# Generated by Django 5.2.4 on 2025-10-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_is_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_important', '-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
