# Generated by Django 5.2.4 on 2025-11-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0025_profile_invitee_profile_partner_profile_queue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile_partner',
            name='account_link',
        ),
        migrations.RemoveField(
            model_name='profile_partner',
            name='account_link',
        ),
        migrations.AddField(
            model_name='historicalprofile_partner',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Реферальный код'),
        ),
        migrations.AddField(
            model_name='historicalprofile_partner',
            name='referral_link',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Реферальная ссылка'),
        ),
        migrations.AddField(
            model_name='historicalprofile_partner',
            name='referred',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Приглашен пользователем'),
        ),
        migrations.AddField(
            model_name='profile_partner',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Реферальный код'),
        ),
        migrations.AddField(
            model_name='profile_partner',
            name='referral_link',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Реферальная ссылка'),
        ),
        migrations.AddField(
            model_name='profile_partner',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Приглашен пользователем'),
        ),
    ]
