# Generated by Django 5.2.4 on 2025-10-21 22:24

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0025_profile_address_profile_invitee_profile_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile_address',
            name='act_street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[personal_account.models.validate_no_english], verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='historicalprofile_address',
            name='reg_street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[personal_account.models.validate_no_english], verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[personal_account.models.validate_no_english], verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, validators=[personal_account.models.validate_no_english], verbose_name='Улица'),
        ),
    ]
