# Generated by Django 5.2.4 on 2025-11-12 20:14

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0026_remove_historicalprofile_partner_account_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile_queue',
            name='additional_status',
            field=models.CharField(choices=[('', '--- Ничего не выбрано ---'), ('В очереди', 'В очереди'), ('На оформлении', 'На оформлении'), ('Формирование 35%', 'Формирование 35%'), ('Формирование 100%', 'Формирование 100%'), ('Должник', 'Должник'), ('Отсутствуют документы', 'Отсутствуют документы'), ('Процесс исключения', 'Процесс исключения'), ('Заявление пайщика', 'Заявление пайщика'), ('Решение совета', 'Решение совета'), ('Завершение целевой программы', 'Завершение целевой программы')], default='', max_length=30, verbose_name='Дополнительный статус'),
        ),
        migrations.AddField(
            model_name='historicalprofile_queue',
            name='consultant_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5'), (6, 'Уровень 6'), (7, 'Уровень 7'), (8, 'Уровень 8'), (9, 'Уровень 9'), (10, 'Уровень 10')], default=None, null=True, validators=[personal_account.models.validate_consultant_level], verbose_name='Уровень консультанта'),
        ),
        migrations.AddField(
            model_name='profile_queue',
            name='additional_status',
            field=models.CharField(choices=[('', '--- Ничего не выбрано ---'), ('В очереди', 'В очереди'), ('На оформлении', 'На оформлении'), ('Формирование 35%', 'Формирование 35%'), ('Формирование 100%', 'Формирование 100%'), ('Должник', 'Должник'), ('Отсутствуют документы', 'Отсутствуют документы'), ('Процесс исключения', 'Процесс исключения'), ('Заявление пайщика', 'Заявление пайщика'), ('Решение совета', 'Решение совета'), ('Завершение целевой программы', 'Завершение целевой программы')], default='', max_length=30, verbose_name='Дополнительный статус'),
        ),
        migrations.AddField(
            model_name='profile_queue',
            name='consultant_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5'), (6, 'Уровень 6'), (7, 'Уровень 7'), (8, 'Уровень 8'), (9, 'Уровень 9'), (10, 'Уровень 10')], default=None, null=True, validators=[personal_account.models.validate_consultant_level], verbose_name='Уровень консультанта'),
        ),
        migrations.AlterField(
            model_name='historicalprofile_queue',
            name='status',
            field=models.CharField(choices=[('Обработка', 'Обработка'), ('Кандидат', 'Кандидат'), ('Член платёжного кооператива', 'Член платёжного кооператива'), ('Пайщик', 'Пайщик'), ('Консультант', 'Консультант'), ('Исключён', 'Исключён'), ('Архив', 'Архив')], default='Обработка', max_length=30, verbose_name='Основоной статус пользователя'),
        ),
        migrations.AlterField(
            model_name='profile_queue',
            name='status',
            field=models.CharField(choices=[('Обработка', 'Обработка'), ('Кандидат', 'Кандидат'), ('Член платёжного кооператива', 'Член платёжного кооператива'), ('Пайщик', 'Пайщик'), ('Консультант', 'Консультант'), ('Исключён', 'Исключён'), ('Архив', 'Архив')], default='Обработка', max_length=30, verbose_name='Основоной статус пользователя'),
        ),
    ]
