# Generated by Django 5.2.4 on 2025-10-08 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0028_alter_historicalprofile_parther_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='parther_name',
            field=models.CharField(blank=True, default='', max_length=60, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'ФИО партнёра может содержать только русские буквы и пробелы')], verbose_name='Фамилия и имя партнёра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parther_name',
            field=models.CharField(blank=True, default='', max_length=60, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'ФИО партнёра может содержать только русские буквы и пробелы')], verbose_name='Фамилия и имя партнёра'),
        ),
    ]
