# Generated by Django 5.2.4 on 2025-11-13 17:06

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0029_alter_historicalprofile_queue_additional_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile_queue',
            name='consultant_level',
        ),
        migrations.RemoveField(
            model_name='profile_queue',
            name='consultant_level',
        ),
        migrations.AddField(
            model_name='historicalprofile_partner',
            name='consultant_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5'), (6, 'Уровень 6'), (7, 'Уровень 7'), (8, 'Уровень 8'), (9, 'Уровень 9'), (10, 'Уровень 10')], default=None, null=True, validators=[personal_account.models.validate_consultant_level], verbose_name='Уровень консультанта'),
        ),
        migrations.AddField(
            model_name='profile_partner',
            name='consultant_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3'), (4, 'Уровень 4'), (5, 'Уровень 5'), (6, 'Уровень 6'), (7, 'Уровень 7'), (8, 'Уровень 8'), (9, 'Уровень 9'), (10, 'Уровень 10')], default=None, null=True, validators=[personal_account.models.validate_consultant_level], verbose_name='Уровень консультанта'),
        ),
    ]
