# Generated by Django 5.2.4 on 2025-10-09 21:53

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0029_alter_historicalprofile_parther_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='document_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='document_photo',
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='document_photo_main',
            field=models.TextField(blank=True, default='', max_length=100, null=True, validators=[personal_account.models.clean_document_photo], verbose_name='Фото главной старницы'),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='document_photo_reg',
            field=models.TextField(blank=True, default='', max_length=100, null=True, validators=[personal_account.models.clean_document_photo], verbose_name='Фото прописки'),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='status',
            field=models.CharField(choices=[('Обработка', 'Обработка')], default='Обработка', max_length=25, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_photo_main',
            field=models.ImageField(blank=True, default='', null=True, upload_to=personal_account.models.profile_doc_upload_path, validators=[personal_account.models.clean_document_photo], verbose_name='Фото главной старницы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_photo_reg',
            field=models.ImageField(blank=True, default='', null=True, upload_to=personal_account.models.profile_doc_upload_path, validators=[personal_account.models.clean_document_photo], verbose_name='Фото прописки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Обработка', 'Обработка')], default='Обработка', max_length=25, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='profile_address',
            name='info',
            field=models.BooleanField(default=False, max_length=1, null=True),
        ),
    ]
