# Generated by Django 5.2.4 on 2025-10-09 22:43

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0030_remove_historicalprofile_document_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='issued_by_whom',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Орган, выдавший документ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='issued_by_whom',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Орган, выдавший документ'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Редактирование'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='price_in_queue',
            field=models.CharField(blank=True, default='', max_length=15, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта при переходе в очередь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Редактирование'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price_in_queue',
            field=models.CharField(blank=True, default='', max_length=15, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта при переходе в очередь'),
        ),
    ]
