# Generated by Django 5.2.4 on 2025-11-13 19:22

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0030_remove_historicalprofile_queue_consultant_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile_queue',
            name='agree_to_consultant',
            field=models.BooleanField(default=False, null=True, verbose_name='Согдасие на присвоение статуса консультанта'),
        ),
        migrations.AddField(
            model_name='historicalprofile_queue',
            name='consultant_contract_photo',
            field=models.TextField(blank=True, default='', max_length=100, null=True, validators=[personal_account.models.clean_document_photo], verbose_name='Заявление консультанта'),
        ),
        migrations.AddField(
            model_name='profile_queue',
            name='agree_to_consultant',
            field=models.BooleanField(default=False, null=True, verbose_name='Согдасие на присвоение статуса консультанта'),
        ),
        migrations.AddField(
            model_name='profile_queue',
            name='consultant_contract_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=personal_account.models.contract_photo_upload_path, validators=[personal_account.models.clean_document_photo], verbose_name='Заявление консультанта'),
        ),
        migrations.AlterField(
            model_name='historicalprofile_queue',
            name='status',
            field=models.CharField(choices=[('Обработка', 'Обработка'), ('Кандидат', 'Кандидат'), ('Член потребительского кооператива', 'Член потребительского кооператива'), ('Пайщик', 'Пайщик'), ('Консультант', 'Консультант'), ('Исключён', 'Исключён'), ('Архив', 'Архив')], default='Обработка', max_length=36, verbose_name='Основоной статус пользователя'),
        ),
        migrations.AlterField(
            model_name='profile_queue',
            name='status',
            field=models.CharField(choices=[('Обработка', 'Обработка'), ('Кандидат', 'Кандидат'), ('Член потребительского кооператива', 'Член потребительского кооператива'), ('Пайщик', 'Пайщик'), ('Консультант', 'Консультант'), ('Исключён', 'Исключён'), ('Архив', 'Архив')], default='Обработка', max_length=36, verbose_name='Основоной статус пользователя'),
        ),
    ]
