# Generated by Django 5.2.4 on 2025-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0031_historicalprofile_queue_agree_to_consultant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile_queue',
            name='additional_status',
            field=models.CharField(blank=True, choices=[('', '--- Ничего не выбрано ---'), ('В очереди', 'В очереди'), ('На оформлении', 'На оформлении'), ('Формирование 35%', 'Формирование 35%'), ('Формирование 100%', 'Формирование 100%'), ('Должник', 'Должник'), ('Отсутствуют документы', 'Отсутствуют документы'), ('Процесс исключения', 'Процесс исключения'), ('Заявление пайщика', 'Заявление пайщика'), ('Решение совета', 'Решение совета'), ('Завершение целевой программы', 'Завершение целевой программы')], default='', max_length=30, verbose_name='Дополнительный статус'),
        ),
        migrations.AlterField(
            model_name='profile_queue',
            name='additional_status',
            field=models.CharField(blank=True, choices=[('', '--- Ничего не выбрано ---'), ('В очереди', 'В очереди'), ('На оформлении', 'На оформлении'), ('Формирование 35%', 'Формирование 35%'), ('Формирование 100%', 'Формирование 100%'), ('Должник', 'Должник'), ('Отсутствуют документы', 'Отсутствуют документы'), ('Процесс исключения', 'Процесс исключения'), ('Заявление пайщика', 'Заявление пайщика'), ('Решение совета', 'Решение совета'), ('Завершение целевой программы', 'Завершение целевой программы')], default='', max_length=30, verbose_name='Дополнительный статус'),
        ),
    ]
