# Generated by Django 5.2.4 on 2025-11-15 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0032_alter_historicalprofile_queue_additional_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('notification_type', models.CharField(default='Системное', max_length=20, verbose_name='Тип уведомления')),
                ('status', models.CharField(blank=True, choices=[('', '--- Ничего не выбрано ---'), ('Обработка', 'Обработка'), ('Кандидат', 'Кандидат'), ('Член потребительского кооператива', 'Член потребительского кооператива'), ('Пайщик', 'Пайщик'), ('Консультант', 'Консультант'), ('Исключён', 'Исключён'), ('Архив', 'Архив')], default='', max_length=36, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=2, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Системное уведомление',
                'verbose_name_plural': 'Системные уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сообщение для пользователя')),
            ],
            options={
                'verbose_name': 'Уведомление о сообщениях',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'is_read', 'created_at'], name='personal_ac_to_user_36e19b_idx'), models.Index(fields=['created_at'], name='personal_ac_created_d1209d_idx')],
            },
        ),
    ]
