# Generated by Django 5.2.4 on 2025-11-18 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0033_systemnotification_messagenotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagenotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Личное сообщение', 'verbose_name_plural': 'Личные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='systemnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Системное сообщение', 'verbose_name_plural': 'Системные сообщения'},
        ),
        migrations.AlterField(
            model_name='messagenotification',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notification', to=settings.AUTH_USER_MODEL, verbose_name='Сообщение для пользователя'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
